name: search_repository
description: A Dart Repository which manages the search domain.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.1.0
  built_collection: ^5.1.0
  # Etc
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.0.5
  built_value_generator: ^8.1.0
  mocktail: ^0.1.4
  test: ^1.16.4
  pedantic: ^1.11.1
  analyzer: ^1.7.2
